#!/usr/bin/env python3
"""Regenerate the TEST-ONLY key set used by the emulator tests.

These keys are public on purpose. A firmware built with -DBL_TEST_KEYS=ON trusts
them and nothing else, so they exist only so CI can sign images and answer
SecurityAccess. The release build never includes them. Seeds are fixed so the
output is reproducible.
"""
import hashlib
import os

import nacl.signing

HERE = os.path.dirname(os.path.abspath(__file__))
seed = hashlib.sha256(b"three-tier-bootloader TEST signing key").digest()
enck = hashlib.sha256(b"three-tier-bootloader TEST chacha20 key").digest()
seck = hashlib.sha256(b"three-tier-bootloader TEST securityaccess key").digest()[:16]
sk = nacl.signing.SigningKey(seed)
pub = bytes(sk.verify_key)

open(os.path.join(HERE, "bl_private.bin"), "wb").write(seed)
open(os.path.join(HERE, "bl_public.bin"), "wb").write(pub)
open(os.path.join(HERE, "bl_enckey.bin"), "wb").write(enck)
open(os.path.join(HERE, "bl_seckey.bin"), "wb").write(seck)


def c_array(name, data):
    rows = []
    for i in range(0, len(data), 8):
        rows.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 8]))
    return "static const uint8_t %s[32] = {\n" % name + ",\n".join(rows) + "\n};\n"


def c_define(name, data):
    lo = ", ".join("0x%02X" % b for b in data[:8])
    hi = ", ".join("0x%02X" % b for b in data[8:])
    return "#define %s { \\\n    %s, \\\n    %s }\n" % (name, lo, hi)


with open(os.path.join(HERE, "bl_test_keys.h"), "w", newline="\n") as f:
    f.write("/* TEST-ONLY keys, generated by make_test_keys.py. Never use in a release. */\n")
    f.write(c_array("BL_PUBLIC_KEY", pub))
    f.write("\n")
    f.write(c_array("BL_ENC_KEY", enck))

with open(os.path.join(HERE, "bl_test_seckey.h"), "w", newline="\n") as f:
    f.write("/* TEST-ONLY SecurityAccess key, generated by make_test_keys.py. Never use in a release. */\n")
    f.write(c_define("BL_SEC_KEY_BYTES", seck))

print("test keys written to", HERE)
